#! /usr/bin/env bash

apt-get update > /dev/null

apt-get install --yes --force-yes libssl-dev libmagickcore-dev libmagickwand-dev libncurses-dev libreadline-dev
apt-get install --yes --force-yes dh-make dpkg-dev devscripts

